theme: minima
# _config.yml
title: mo博客


description: 一个记录学习的站点
navigation:  # 自定义导航栏链接
  - title: 首页
    url: /README.md
  - title: 关于Git
    url: /关于Git/Git.1学习.md
  - title: SQL
    url: /SQL/0x3盲注.md
